"""change_reviewed_to_boolean

Revision ID: be0794439803
Revises: 
Create Date: 2026-06-03 04:15:58.779154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be0794439803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('self_facts',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('short_description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('summary',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        # Note: index on 'email' retained as-is — cannot drop/recreate while
        # foreign key constraints from education/experience tables reference it.

    # Two-step for testimony.reviewed: convert existing 'Y'/'N' strings to 1/0
    # before MySQL can safely ALTER the column to BOOL.
    op.execute("UPDATE testimony SET reviewed = 1 WHERE reviewed = 'Y'")
    op.execute("UPDATE testimony SET reviewed = 0 WHERE reviewed = 'N'")

    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.alter_column('reviewed',
               existing_type=mysql.CHAR(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.alter_column('reviewed',
               existing_type=sa.Boolean(),
               type_=mysql.CHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('about', schema=None) as batch_op:
        # Note: skipping index rename (retained as-is due to FK constraints).
        batch_op.alter_column('summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('short_description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('self_facts',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
